name: mini_collection_poc
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  native_device_orientation: ^1.1.4
  tilt: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  assets:
    - assets/flaticon/
    - assets/unsplash/
  uses-material-design: true
